create table  spotify.base_popular_spotify_songs(
track_name            varchar(250),
artists_name          varchar(250),
artist_count          int, 
released_year         int, 
released_month        int, 
released_day          int, 
in_spotify_playlists  int, 
in_spotify_charts     int, 
streams               varchar(250),
in_apple_playlists    int,
in_apple_charts       int, 
in_deezer_playlists   varchar(250),
in_deezer_charts      int, 
in_shazam_charts      varchar(250),
bpm                   int, 
`key`                 varchar(250),
mode                  varchar(250),
danceability          int, 
valence               int, 
energy                int, 
acousticness          int, 
instrumentalness      int, 
liveness              int, 
speechiness           int 
);